const SETTINGS_KEYS = ["sticker_cache_v2", "sticker_imported_v1", "sticker_favorites", "sticker_recents", "sticker_broken_preview_ids_v1", "sticker_usage_metrics_v1", "sticker_popup_preferences_v1", "sticker_custom_order_v1", "sticker_hidden_preview_ids_v1", "sticker_trash_v1", "sticker_pinned_preview_ids_v1", "sticker_pack_preferences_v1"];
const MANAGEMENT_KEYS = ["sticker_popup_preferences_v1", "sticker_custom_order_v1", "sticker_hidden_preview_ids_v1", "sticker_trash_v1", "sticker_pinned_preview_ids_v1", "sticker_pack_preferences_v1"];
const TRASH_RETENTION_MS = 30 * 24 * 60 * 60 * 1000;
let state = {}; let selectedIds = new Set(); let draggedId = "";

function array(value) { return Array.isArray(value) ? value : []; }
function popupPrefs(value) { const p = value && typeof value === "object" ? value : {}; return { showStats:p.showStats!==false, showQuickReactions:p.showQuickReactions!==false, showUpload:p.showUpload!==false, showCacheControls:p.showCacheControls!==false, showUsage:p.showUsage!==false }; }
function packPrefs(value) { return value && typeof value === "object" ? value : {}; }
function trashItems(value) { return array(value).filter((item) => item && item.previewId && item.deletedAt); }
function stickers() { const byId = new Map(); [...array(state.sticker_cache_v2), ...array(state.sticker_imported_v1)].forEach((sticker) => { if (sticker && sticker.previewId) byId.set(String(sticker.previewId), sticker); }); return [...byId.values()]; }
function importedIds() { return new Set(array(state.sticker_imported_v1).map((s) => String(s.previewId))); }
function trashedIds() { return new Set(trashItems(state.sticker_trash_v1).map((item) => String(item.previewId))); }
function hiddenIds() { return new Set(array(state.sticker_hidden_preview_ids_v1).map(String)); }
function isVisible(sticker) { const pref=packPrefs(state.sticker_pack_preferences_v1)[sticker.pack]||{}; return !trashedIds().has(String(sticker.previewId)) && !hiddenIds().has(String(sticker.previewId)) && pref.hidden!==true; }
function ordered(list) { const order=array(state.sticker_custom_order_v1).map(String); const rank=new Map(order.map((id,i)=>[id,i])); return list.slice().sort((a,b)=> (rank.has(String(a.previewId)) ? rank.get(String(a.previewId)) : order.length + list.indexOf(a)) - (rank.has(String(b.previewId)) ? rank.get(String(b.previewId)) : order.length + list.indexOf(b))); }
function setStatus(message) { const node=document.getElementById("status"); if(node) node.textContent=message; }
function save(data) { Object.assign(state,data); return chrome.storage.local.set(data).then(() => notifyContent()).catch((error)=>{ setStatus(error.message||"Không thể lưu settings."); throw error; }); }
function notifyContent() { return chrome.tabs.query({active:true,currentWindow:true}).then((tabs)=>tabs[0]&&tabs[0].id ? chrome.tabs.sendMessage(tabs[0].id,{action:"refresh_sticker_preferences"}).catch(()=>null) : null); }
function label(sticker) { const p=packPrefs(state.sticker_pack_preferences_v1)[sticker.pack]||{}; return p.name || sticker.pack || sticker.source || "legacy"; }
function escapeHtml(value) { const d=document.createElement("div"); d.textContent=String(value||""); return d.innerHTML; }
function nextOrder(ids, id, destination) { const currentIndex=ids.indexOf(id); if(currentIndex<0)return ids; const next=ids.filter((item)=>item!==id); const index=destination==="top"?0:destination==="bottom"?next.length:Math.min(next.length,Math.max(0,currentIndex+destination)); next.splice(index,0,id); return next; }
function moveOrder(id, destination) { const ids=ordered(stickers().filter(isVisible)).map((s)=>String(s.previewId)); return save({sticker_custom_order_v1:nextOrder(ids,id,destination)}).then(render); }
function renderOverview() { const visible=stickers().filter(isVisible); const data=[ ["Tổng sticker",stickers().length], ["Imported",array(state.sticker_imported_v1).length], ["Favorite",array(state.sticker_favorites).filter((id)=>isVisible({previewId:id,pack:""})).length], ["Recent",array(state.sticker_recents).filter((s)=>isVisible(s)).length], ["Thùng rác",trashItems(state.sticker_trash_v1).length] ]; document.getElementById("overviewStats").innerHTML=data.map(([name,value])=>`<div class="stat"><span>${name}</span><b>${value}</b></div>`).join(""); }
function renderPopupPreferences() { const names={showStats:"Thống kê sticker",showQuickReactions:"Quick Reactions",showUpload:"Khu vực upload sticker",showCacheControls:"Nút cache",showUsage:"Thống kê usage cục bộ"}; const prefs=popupPrefs(state.sticker_popup_preferences_v1); const holder=document.getElementById("popupPreferences"); holder.replaceChildren(...Object.entries(names).map(([key,name])=>{const l=document.createElement("label"), input=document.createElement("input");input.type="checkbox";input.checked=prefs[key];input.addEventListener("change",()=>save({sticker_popup_preferences_v1:{...popupPrefs(state.sticker_popup_preferences_v1),[key]:input.checked}}).then(()=>setStatus("Đã lưu hiển thị Popup.")));l.append(input,name);return l;})); }
function createStickerCard(sticker) { const id=String(sticker.previewId), card=document.createElement("article");card.className="sticker"+(selectedIds.has(id)?" selected":"");card.draggable=true;card.dataset.previewId=id; card.innerHTML=`<div class="sticker-image"><img alt="" src="${escapeHtml(sticker.url)}"></div><div class="name" title="${escapeHtml(sticker.name||id)}">${escapeHtml(sticker.name||id)}</div><small title="${escapeHtml(label(sticker))} · ${escapeHtml(sticker.source||"")}">${escapeHtml(label(sticker))} · ${escapeHtml(sticker.source||"")}</small>`; const actions=document.createElement("div");actions.className="actions"; const select=document.createElement("button");select.className="select-action";select.textContent=selectedIds.has(id)?"Bỏ chọn":"Chọn";select.onclick=()=>{selectedIds.has(id)?selectedIds.delete(id):selectedIds.add(id);renderManager();}; const orderActions=document.createElement("div");orderActions.className="order-actions"; const up=document.createElement("button");up.textContent="↑";up.title="Move up";up.setAttribute("aria-label","Move up");up.onclick=()=>moveOrder(id,-1); const down=document.createElement("button");down.textContent="↓";down.title="Move down";down.setAttribute("aria-label","Move down");down.onclick=()=>moveOrder(id,1); const top=document.createElement("button");top.textContent="Top";top.onclick=()=>moveOrder(id,"top"); const bottom=document.createElement("button");bottom.textContent="Bottom";bottom.onclick=()=>moveOrder(id,"bottom"); orderActions.append(up,down,top,bottom);actions.append(select,orderActions);card.append(actions);card.addEventListener("dragstart",()=>{draggedId=id;});card.addEventListener("dragover",(e)=>e.preventDefault());card.addEventListener("drop",()=>{if(!draggedId||draggedId===id)return;const ids=ordered(stickers().filter(isVisible)).map((s)=>String(s.previewId)).filter((x)=>x!==draggedId);ids.splice(ids.indexOf(id),0,draggedId);save({sticker_custom_order_v1:ids}).then(render);});return card; }
function renderManager() { const query=document.getElementById("stickerSearch").value.toLowerCase(); const mode=document.getElementById("stickerFilter").value; const hidden=hiddenIds(), trashed=trashedIds(); let list=stickers().filter((s)=>{const text=[s.name,s.previewId,s.pack,s.source,...array(s.tags)].join(" ").toLowerCase();if(!text.includes(query))return false;if(mode==="visible")return isVisible(s);if(mode==="hidden")return hidden.has(String(s.previewId))||trashed.has(String(s.previewId));return true;});list=ordered(list);document.getElementById("stickerGrid").replaceChildren(...list.map(createStickerCard));document.getElementById("selectionInfo").textContent=`${selectedIds.size} đã chọn`; }
function renderTrash() { const byId=new Map(stickers().map((s)=>[String(s.previewId),s]));const now=Date.now(); const cards=trashItems(state.sticker_trash_v1).map((item)=>{const sticker=byId.get(String(item.previewId))||item.snapshot||item;const card=document.createElement("article");card.className="sticker";const left=Math.max(0,Math.ceil((TRASH_RETENTION_MS-(now-new Date(item.deletedAt).getTime()))/86400000));card.innerHTML=`<div class="sticker-image"><img alt="" src="${escapeHtml(sticker.url||"")}"></div><div class="name" title="${escapeHtml(sticker.name||item.previewId)}">${escapeHtml(sticker.name||item.previewId)}</div><small title="${escapeHtml(item.originalPack||sticker.pack||"")}">${escapeHtml(item.originalPack||sticker.pack||"")}</small><small class="trash-days">Còn ${left} ngày</small>`;const restore=document.createElement("button");restore.textContent="Khôi phục";restore.onclick=()=>restoreTrash([String(item.previewId)]);card.append(restore);return card;});const target=document.getElementById("trashGrid");target.replaceChildren(...cards);if(!cards.length)target.textContent="Thùng rác trống."; }
function renderPacks() { const packs=[...new Set(stickers().map((s)=>s.pack).filter(Boolean))].sort();const prefs=packPrefs(state.sticker_pack_preferences_v1), target=document.getElementById("packManager");target.replaceChildren(...packs.map((pack)=>{const p=prefs[pack]||{}, row=document.createElement("div"), check=document.createElement("input"), name=document.createElement("input");check.type="checkbox";check.checked=!p.hidden;name.type="text";name.value=p.name||"";name.placeholder=pack;check.onchange=()=>save({sticker_pack_preferences_v1:{...packPrefs(state.sticker_pack_preferences_v1),[pack]:{...p,hidden:!check.checked}}}).then(render);name.onchange=()=>save({sticker_pack_preferences_v1:{...packPrefs(state.sticker_pack_preferences_v1),[pack]:{...p,name:name.value.trim(),hidden:p.hidden===true}}}).then(render);row.className="row";row.append(check,document.createTextNode(pack),name);return row;}));const broken=array(state.sticker_broken_preview_ids_v1);document.getElementById("healthSummary").textContent=broken.length?`${broken.length} ảnh lỗi được phát hiện.`:"Không có ảnh lỗi đã biết."; }
function render(){renderOverview();renderPopupPreferences();renderManager();renderTrash();renderPacks();}
function moveToTrash(ids) { const all=new Map(stickers().map((s,i)=>[String(s.previewId),{s,i}]));const existing=trashItems(state.sticker_trash_v1), seen=new Set(existing.map((x)=>String(x.previewId)));const additions=ids.filter((id)=>all.has(id)&&!seen.has(id)).map((id)=>{const {s,i}=all.get(id);return{previewId:id,snapshot:s,deletedAt:new Date().toISOString(),originalPack:s.pack||"",originalOrderIndex:i};});const blocked=new Set([...trashedIds(),...ids]);return save({sticker_trash_v1:[...existing,...additions],sticker_favorites:array(state.sticker_favorites).filter((id)=>!blocked.has(String(id))),sticker_recents:array(state.sticker_recents).filter((s)=>!blocked.has(String(s.previewId)))}).then(()=>{selectedIds.clear();setStatus(`Đã chuyển ${additions.length} sticker vào Thùng rác — Ctrl/Cmd + Z để hoàn tác.`);render();}); }
function restoreTrash(ids) { const wanted=new Set(ids), restored=trashItems(state.sticker_trash_v1).filter((item)=>wanted.has(String(item.previewId)));const hidden=new Set(hiddenIds());restored.forEach((item)=>hidden.delete(String(item.previewId)));return save({sticker_trash_v1:trashItems(state.sticker_trash_v1).filter((item)=>!wanted.has(String(item.previewId))),sticker_hidden_preview_ids_v1:[...hidden]}).then(()=>{setStatus(`Đã khôi phục ${restored.length} sticker.`);render();}); }
function cleanupTrash() { const expiry=Date.now()-TRASH_RETENTION_MS;const keep=trashItems(state.sticker_trash_v1).filter((item)=>new Date(item.deletedAt).getTime()>expiry);if(keep.length!==trashItems(state.sticker_trash_v1).length)return chrome.storage.local.set({sticker_trash_v1:keep}).then(()=>{state.sticker_trash_v1=keep;});return Promise.resolve(); }
function exportPreferences(){const payload={version:1,exportedAt:new Date().toISOString(),preferences:Object.fromEntries(MANAGEMENT_KEYS.map((key)=>[key,state[key]??(key==="sticker_popup_preferences_v1"?popupPrefs():[])]))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="chatwork-sticker-preferences.json";a.click();URL.revokeObjectURL(url);}
function bind(){document.querySelectorAll("[data-jump]").forEach((b)=>b.onclick=()=>document.getElementById(b.dataset.jump).scrollIntoView({behavior:"smooth"}));document.getElementById("stickerSearch").oninput=renderManager;document.getElementById("stickerFilter").onchange=renderManager;document.getElementById("selectVisible").onclick=()=>{ordered(stickers().filter(isVisible)).forEach((s)=>selectedIds.add(String(s.previewId)));renderManager();};document.getElementById("hideSelected").onclick=()=>save({sticker_hidden_preview_ids_v1:[...new Set([...hiddenIds(),...selectedIds])]}).then(()=>{selectedIds.clear();render();});document.getElementById("trashSelected").onclick=()=>moveToTrash([...selectedIds]);document.getElementById("resetOrder").onclick=()=>save({sticker_custom_order_v1:[]}).then(()=>{setStatus("Đã reset thứ tự.");render();});document.getElementById("trashBroken").onclick=()=>moveToTrash(array(state.sticker_broken_preview_ids_v1).map(String));document.getElementById("emptyTrash").onclick=()=>{const ids=trashItems(state.sticker_trash_v1).map((x)=>String(x.previewId));const eligible=ids.filter((id)=>importedIds().has(id));if(!eligible.length)return setStatus("Không có sticker imported nào để xóa vĩnh viễn.");if(!confirm(`Xóa vĩnh viễn ${eligible.length} sticker imported? Không thể hoàn tác.`))return;save({sticker_imported_v1:array(state.sticker_imported_v1).filter((s)=>!eligible.includes(String(s.previewId))),sticker_trash_v1:trashItems(state.sticker_trash_v1).filter((x)=>!eligible.includes(String(x.previewId)))}).then(()=>{setStatus(`Đã xóa vĩnh viễn ${eligible.length} sticker imported.`);render();});};document.getElementById("exportPreferences").onclick=exportPreferences;document.getElementById("importPreferences").onchange=(e)=>{const file=e.target.files&&e.target.files[0];if(!file)return;file.text().then(JSON.parse).then((payload)=>{if(!payload||!payload.preferences)throw new Error("Tệp preferences không hợp lệ.");const data={};MANAGEMENT_KEYS.forEach((key)=>{if(Object.prototype.hasOwnProperty.call(payload.preferences,key))data[key]=payload.preferences[key];});return save(data);}).then(()=>{setStatus("Đã import preferences.");render();}).catch((err)=>setStatus(err.message));};document.querySelectorAll("[data-reset]").forEach((b)=>b.onclick=()=>{const map={ui:["sticker_popup_preferences_v1"],order:["sticker_custom_order_v1"],trash:["sticker_trash_v1"],usage:["sticker_usage_metrics_v1"]};const data=Object.fromEntries(map[b.dataset.reset].map((key)=>[key,key==="sticker_popup_preferences_v1"?popupPrefs():[]]));save(data).then(render);});document.addEventListener("keydown",(e)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"&&trashItems(state.sticker_trash_v1).length){e.preventDefault();const last=trashItems(state.sticker_trash_v1).slice(-1)[0];restoreTrash([String(last.previewId)]);}if(e.key==="Escape")selectedIds.clear(),renderManager();});}
document.addEventListener("DOMContentLoaded",()=>{bind();chrome.storage.local.get(SETTINGS_KEYS).then((data)=>{state=data;return cleanupTrash();}).then(render).catch((error)=>setStatus(error.message||"Không thể tải settings."));});
if(typeof global!=="undefined"){global.orderedSettingsStickers=ordered;global.settingsIsVisible=isVisible;global.settingsNextOrder=nextOrder;}
